version: '3.7'

services:
  scrapyrt:
    build: ./project
    image: akshay/scrapyrt
    ports:
      - 9080:9080

  handler:
    build: ./handler
    image: akshay/handler
    command: python handler.py
    ports:
      - 8001:8001

  rq-workers:
    image: akshay/handler
    command: rq worker -u redis://redis-server:6379 high default low
    restart: unless-stopped
    deploy:
      replicas: 3
    
  redis-server:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - 6379:6379